config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages

  validates :name, presence: true

  def show_last_massage
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :members
  has_many :groups, through: :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameter, if: :devise_controller?

  protected

  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :set_group, only: [:edit, :update]

  def index
    redirect_to root_path unless user_signed_in?
  end

  def new
    @group =Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json {@new_messages = @messages.where('id > ?', params[:id])}
    end
  end

  def create
    @message = @group.messages.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      else
        format.html { @messages = @group.messages.includes(:user),
        flash.now[:alert] = 'メッセージを入力してください'
        render :index }
        format.json
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: [:index, :edit]

  def index
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def set_users
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label' do
        グループ名
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: "chat-group-form__label" do
        チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search
        = f.text_field :name, class: 'chat-group-form__input', id: 'user-search-field', placeholder: '追加したいユーザー名を入力してください', value: "", name: "keyword"
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, class: "chat-group-form__label" do
        チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        - group.users.each do |member|
          .chat-group-user.clearfix#chat-group-user-22
            %p.chat-group-user__name
              = member.name
              = f.hidden_field :user_id, name: "group[user_ids][]", value: member.id

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: {group: @group }

app/views/groups/index.html.haml
.wrapper

  = render 'shared/side-bar'

.chat-monitor
  .chat-monitor__group-details
    .chat-monitor__group-details__name

  .chat-monitor__content
    = render partial: 'messages/message', collection: @messages

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', {group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_group-menus.html.haml
.side-bar__chat
  .side-bar__chat__title
    %h1
      = group_name
  .side-bar__chat__message
    %p
      = message_preview

app/views/messages/_message.html.haml
.chat-monitor__content__details{data: {id: message.id} }
  .chat-monitor__content__details__user-name
    %p
      = message.user.name
  .chat-monitor__content__details__time
    %p
      = message.created_at.strftime("%Y/%m/%d %H:%M:%S")
  .chat-monitor__content__details__message
    - if message.content.present?
      %p
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
= render partial: "shared/side-bar"

.chat-monitor
  .chat-monitor__group-details
    .chat-monitor__group-details__name
      %p
        = @group.name
    .chat-monitor__group-details__edit
      = link_to edit_group_path(@group.id) do
        %span
          Edit
    .chat-monitor__group-details__member
      %p
        Member:
        - @group.users.each do |group|
          = group.name
  .chat-monitor__content
    = render partial: 'message', collection: @messages


  .form
    = form_for [@group, @message] do |f|
      = f.text_field :content, class: 'form__message', placeholder: 'type a message'
      .form__mask
        = f.label :image, class: 'form__mask__image' do
          = fa_icon 'picture-o', class: 'upload-icon'
          = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'form__submit'

app/views/shared/_chat.html.haml
.chat-monitor
  .chat-monitor__group-details
    .chat-monitor__group-details__name
      %p
        = @group.name
    .chat-monitor__group-details__edit
      = link_to edit_group_path(current_user) do
        %span
          Edit
  .chat-monitor__content

  .chat-monitor__sending-massage

  .chat-monitor
    .form
      = form_for [@group, @message] do |f|
        = f.text_field :content, class: 'form__message', placeholder: 'type a message'
        .form__mask
          = f.label :image, class: 'form__mask__image' do
            = fa_icon 'picture-o', class: 'upload-icon'
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'

app/views/shared/_side-bar.html.haml
.side-bar
  .side-bar__user
    .side-bar__user__name
      %p
        = current_user.name
    .side-bar__user__edit-icon
      %i.list
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %i.list
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'

  .side-bar__chat
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .side-bar__chat__title
          = group.name
        .side-bar__chat__message
          = group.show_last_massage

app/views/users/_flash-message.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'